; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_l496zg]
platform = ststm32
board = nucleo_l496zg
framework = stm32cube

build_flags =
    -DSTM32L4A6xx
    -DUSE_HAL_DRIVER
    -ICore/Inc
    -IDrivers/STM32L4xx_HAL_Driver/Inc
    -IDrivers/STM32L4xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Device/ST/STM32L4xx/Include
    -IDrivers/CMSIS/Include

build_src_filter =
    +<src/>
    +<Drivers/STM32L4xx_HAL_Driver/Src/>
    +<startup_stm32l4a6xx.s>

upload_protocol = stlink
debug_tool = stlink